apiVersion: v1
kind: Service
metadata:
  name: aijobfinder-backend-service
  namespace: production
spec:
  selector:
    app: aijobfinder-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
