"""add_soft_delete_and_account_deletion_request

Revision ID: 411aed37c597
Revises: 6613a74d23b8
Create Date: 2026-07-13 14:30:47.761871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '411aed37c597'
down_revision: Union[str, Sequence[str], None] = '6613a74d23b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_deletion_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('otp_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('otp_verified', sa.Boolean(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_deletion_requests_id'), 'account_deletion_requests', ['id'], unique=False)
    op.create_index(op.f('ix_account_deletion_requests_user_id'), 'account_deletion_requests', ['user_id'], unique=False)
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_index(op.f('ix_account_deletion_requests_user_id'), table_name='account_deletion_requests')
    op.drop_index(op.f('ix_account_deletion_requests_id'), table_name='account_deletion_requests')
    op.drop_table('account_deletion_requests')
    # ### end Alembic commands ###
