"""Add new_password_hash column

Revision ID: 6613a74d23b8
Revises: fec6d2d61489
Create Date: 2026-07-13 13:12:53.551673

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6613a74d23b8"
down_revision: Union[str, Sequence[str], None] = "fec6d2d61489"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "password_change_requests",
        sa.Column("new_password_hash", sa.String(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("password_change_requests", "new_password_hash")
    # ### end Alembic commands ###
