"""Update Experience and Project models with associations

Revision ID: a719e7f0df01
Revises: 5a77679666cd
Create Date: 2026-07-18 00:42:58.103621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a719e7f0df01'
down_revision: Union[str, Sequence[str], None] = '5a77679666cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experience_projects',
    sa.Column('experience_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('experience_id', 'project_id')
    )
    op.create_table('experience_skills',
    sa.Column('experience_id', sa.String(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('experience_id', 'skill_id')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('proficiency', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_languages_id'), ['id'], unique=False)

    op.create_table('project_skills',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'skill_id')
    )
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('work_model', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('manager_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('order')
        batch_op.drop_column('manager_name')
        batch_op.drop_column('work_model')
        batch_op.drop_column('department')

    op.drop_table('project_skills')
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_languages_id'))

    op.drop_table('languages')
    op.drop_table('experience_skills')
    op.drop_table('experience_projects')
    # ### end Alembic commands ###
