"""social_auth_models

Revision ID: d0498fe6bc72
Revises: 411aed37c597
Create Date: 2026-07-13 15:05:43.064964

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d0498fe6bc72"
down_revision: Union[str, Sequence[str], None] = "411aed37c597"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connected_accounts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum(
                "email",
                "google",
                "github",
                "microsoft",
                "linkedin",
                name="authprovider",
            ),
            nullable=False,
        ),
        sa.Column("provider_user_id", sa.String(), nullable=False),
        sa.Column("provider_email", sa.String(), nullable=True),
        sa.Column("connected_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_connected_accounts_id"), "connected_accounts", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_connected_accounts_provider_user_id"),
        "connected_accounts",
        ["provider_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_connected_accounts_user_id"),
        "connected_accounts",
        ["user_id"],
        unique=False,
    )
    with op.batch_alter_table("users") as batch_op:
        batch_op.add_column(
            sa.Column(
                "auth_provider",
                sa.Enum(
                    "email",
                    "google",
                    "github",
                    "microsoft",
                    "linkedin",
                    name="authprovider",
                ),
                nullable=True,
            )
        )
        batch_op.alter_column(
            "password_hash", existing_type=sa.VARCHAR(), nullable=True
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as batch_op:
        batch_op.alter_column(
            "password_hash", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.drop_column("auth_provider")
    op.drop_index(
        op.f("ix_connected_accounts_user_id"), table_name="connected_accounts"
    )
    op.drop_index(
        op.f("ix_connected_accounts_provider_user_id"), table_name="connected_accounts"
    )
    op.drop_index(op.f("ix_connected_accounts_id"), table_name="connected_accounts")
    op.drop_table("connected_accounts")
    # ### end Alembic commands ###
