"""Add Career Profile models

Revision ID: eb52dda06d2e
Revises: d0498fe6bc72
Create Date: 2026-07-13 16:40:31.828816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb52dda06d2e'
down_revision: Union[str, Sequence[str], None] = 'd0498fe6bc72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_preferences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('dream_companies', sa.String(), nullable=True),
    sa.Column('dream_roles', sa.String(), nullable=True),
    sa.Column('dream_technologies', sa.String(), nullable=True),
    sa.Column('preferred_ai_domains', sa.String(), nullable=True),
    sa.Column('learning_goals', sa.Text(), nullable=True),
    sa.Column('interview_level', sa.String(), nullable=True),
    sa.Column('target_salary', sa.String(), nullable=True),
    sa.Column('target_country', sa.String(), nullable=True),
    sa.Column('career_objectives', sa.Text(), nullable=True),
    sa.Column('job_search_frequency', sa.String(), nullable=True),
    sa.Column('career_growth_priorities', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('ai_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_preferences_id'), ['id'], unique=False)

    op.create_table('career_preferences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('preferred_roles', sa.String(), nullable=True),
    sa.Column('preferred_industries', sa.String(), nullable=True),
    sa.Column('preferred_locations', sa.String(), nullable=True),
    sa.Column('work_setup', sa.String(), nullable=True),
    sa.Column('expected_salary', sa.String(), nullable=True),
    sa.Column('preferred_currency', sa.String(), nullable=True),
    sa.Column('employment_types', sa.String(), nullable=True),
    sa.Column('company_size', sa.String(), nullable=True),
    sa.Column('visa_sponsorship', sa.Boolean(), nullable=True),
    sa.Column('willing_to_relocate', sa.Boolean(), nullable=True),
    sa.Column('travel_willingness', sa.String(), nullable=True),
    sa.Column('preferred_shift', sa.String(), nullable=True),
    sa.Column('availability', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('career_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_career_preferences_id'), ['id'], unique=False)

    op.create_table('certifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('issuer', sa.String(), nullable=False),
    sa.Column('credential_id', sa.String(), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('verification_url', sa.String(), nullable=True),
    sa.Column('certificate_image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certifications_id'), ['id'], unique=False)

    op.create_table('educations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('institution', sa.String(), nullable=False),
    sa.Column('degree', sa.String(), nullable=False),
    sa.Column('major', sa.String(), nullable=True),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('cgpa', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('activities', sa.Text(), nullable=True),
    sa.Column('achievements', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('educations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_educations_id'), ['id'], unique=False)

    op.create_table('experiences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('company_logo_url', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('achievements', sa.Text(), nullable=True),
    sa.Column('technologies', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiences_id'), ['id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_type', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('tech_stack', sa.String(), nullable=True),
    sa.Column('ai_technologies', sa.String(), nullable=True),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('live_demo_url', sa.String(), nullable=True),
    sa.Column('video_demo_url', sa.String(), nullable=True),
    sa.Column('highlights', sa.Text(), nullable=True),
    sa.Column('challenges', sa.Text(), nullable=True),
    sa.Column('achievements', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)

    op.create_table('social_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('portfolio_url', sa.String(), nullable=True),
    sa.Column('kaggle_url', sa.String(), nullable=True),
    sa.Column('leetcode_url', sa.String(), nullable=True),
    sa.Column('codeforces_url', sa.String(), nullable=True),
    sa.Column('hackerrank_url', sa.String(), nullable=True),
    sa.Column('medium_url', sa.String(), nullable=True),
    sa.Column('devto_url', sa.String(), nullable=True),
    sa.Column('youtube_url', sa.String(), nullable=True),
    sa.Column('twitter_url', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('social_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_profiles_id'), ['id'], unique=False)

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parsing_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ai_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('years_of_experience', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cover_banner_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('headline', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('time_zone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('languages', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('employment_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('industry', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('career_level', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('preferred_currency', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('professional_summary', sa.Text(), nullable=True))
        batch_op.drop_column('job_type')
        batch_op.drop_column('work_preference')
        batch_op.drop_column('preferred_companies')
        batch_op.drop_column('highest_education')
        batch_op.drop_column('preferred_role')
        batch_op.drop_column('open_to_relocation')
        batch_op.drop_column('preferred_locations')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_locations', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('open_to_relocation', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('preferred_role', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('highest_education', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('preferred_companies', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('work_preference', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('job_type', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('professional_summary')
        batch_op.drop_column('preferred_currency')
        batch_op.drop_column('career_level')
        batch_op.drop_column('industry')
        batch_op.drop_column('employment_status')
        batch_op.drop_column('languages')
        batch_op.drop_column('time_zone')
        batch_op.drop_column('city')
        batch_op.drop_column('state')
        batch_op.drop_column('country')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('bio')
        batch_op.drop_column('headline')
        batch_op.drop_column('cover_banner_url')
        batch_op.drop_column('profile_picture_url')

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_column('years_of_experience')
        batch_op.drop_column('level')
        batch_op.drop_column('category')

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('ai_summary')
        batch_op.drop_column('parsing_status')
        batch_op.drop_column('version')
        batch_op.drop_column('file_size')
        batch_op.drop_column('file_name')

    with op.batch_alter_table('social_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_profiles_id'))

    op.drop_table('social_profiles')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_id'))

    op.drop_table('projects')
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiences_id'))

    op.drop_table('experiences')
    with op.batch_alter_table('educations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_educations_id'))

    op.drop_table('educations')
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certifications_id'))

    op.drop_table('certifications')
    with op.batch_alter_table('career_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_career_preferences_id'))

    op.drop_table('career_preferences')
    with op.batch_alter_table('ai_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_preferences_id'))

    op.drop_table('ai_preferences')
    # ### end Alembic commands ###
