"""Add password_change_requests table

Revision ID: fec6d2d61489
Revises: 2f8ef7b652ed
Create Date: 2026-07-13 13:11:47.501566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fec6d2d61489'
down_revision: Union[str, Sequence[str], None] = '2f8ef7b652ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_change_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('otp_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_change_requests_id'), 'password_change_requests', ['id'], unique=False)
    op.create_index(op.f('ix_password_change_requests_user_id'), 'password_change_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_change_requests_user_id'), table_name='password_change_requests')
    op.drop_index(op.f('ix_password_change_requests_id'), table_name='password_change_requests')
    op.drop_table('password_change_requests')
    # ### end Alembic commands ###
