{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ai-job-finder.fullname" . }}-postgres
  labels:
    app.kubernetes.io/name: {{ include "ai-job-finder.name" . }}-postgres
spec:
  serviceName: {{ include "ai-job-finder.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ai-job-finder.name" . }}-postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ai-job-finder.name" . }}-postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image }}"
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ai-job-finder.fullname" . }}-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.postgres.persistence.size }}
{{- end }}
