apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "Crown Atlas.fullname" . }}-chroma-pvc
  labels:
    app.kubernetes.io/name: {{ include "Crown Atlas.name" . }}-chroma
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "Crown Atlas.fullname" . }}-uploads-pvc
  labels:
    app.kubernetes.io/name: {{ include "Crown Atlas.name" . }}-uploads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
