{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ai-job-finder.fullname" . }}-redis
  labels:
    app.kubernetes.io/name: {{ include "ai-job-finder.name" . }}-redis
spec:
  serviceName: {{ include "ai-job-finder.fullname" . }}-redis
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ai-job-finder.name" . }}-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ai-job-finder.name" . }}-redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image }}"
          command:
            - redis-server
            - "--requirepass"
            - "$(REDIS_PASSWORD)"
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ai-job-finder.fullname" . }}-secret
                  key: REDIS_PASSWORD
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.redis.persistence.size }}
{{- end }}
